CREATE TABLE USER_TBL(
	ID 		VARCHAR2(50) PRIMARY KEY , 
	PWD		VARCHAR2(50) NOT NULL , 
	NAME    VARCHAR2(50) NOT NULL , 
	POINT   NUMBER       DEFAULT 1000
);

CREATE TABLE BBS_TBL(
	SEQ NUMBER PRIMARY KEY,
	SUBJECT VARCHAR2(50),
	CONTENT VARCHAR2(1000),
	WRITER VARCHAR2(50),
	REGDATE DATE,
	VIEWCNT NUMBER
);

create SEQUENCE BBS_SEQ;

CREATE TABLE REPLY_TBL(
	RSEQ NUMBER PRIMARY KEY,
	SEQ NUMBER REFERENCES BBS_TBL(SEQ),
	RWRITER VARCHAR2(20),
	RCONTENT VARCHAR2(1000),
	RDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE REPLY_SEQ;
